version: 2
jobs:
  build:
    docker:
      - image: nautilusdigital/node-builder:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build

workflows:
  version: 2
  kaboom:
    jobs:
      - build
